.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gleecbtc_qt test_gleecbtc_qt
clean: FORCE
	$(MAKE) -C .. gleecbtc_qt_clean test_gleecbtc_qt_clean
check: FORCE
	$(MAKE) -C .. test_gleecbtc_qt_check
gleecbtc-qt gleecbtc-qt.exe: FORCE
	 $(MAKE) -C .. gleecbtc_qt
